server:
  port: 7777


spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    url: jdbc:postgresql://localhost:1010/library_db
    username: postgres
    password: j@vacefer2005
  jpa:
    open-in-view: true
  liquibase:
    change-log: classpath:liquibase/changelog-master.yaml

redis:
  server:
    urls: redis://localhost:6379
    password: myredispassword

token:
  expiration:
    access-token: 100
    refresh-token: 21600

logging:
  level:
    org:
      springframework:
        security=DEBUG: